name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
‐ name: build-push
  uses: docker/build-push-action@v1.1.0
  with:
    username: ${{ DOCKER_USERNAME }}
    password: ${{ DOCKER_PASSWORD }}
    repository: pierremalherbeznk/sample-flask-for-kong:$(date +%s)
    tags: v1
